name: Acquire activation file
on:
  workflow_dispatch:

jobs:
  Activation:
    name: Request manual activation file
    runs-on: ubuntu-latest
    steps:
      - uses: game-ci/unity-request-activation-file@v2
        id: get-manual-license
        with:
          unityVersion: 2021.2.16f1

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.get-manual-license.outputs.filePath }}
          path: ${{ steps.get-manual-license.outputs.filePath }}
