name: Test

on:
  push:
    branches:
      - main

jobs:
  Test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        id: unity-cache
        with:
          key: /Application/Unity
          path: |
            /Application/Unity

      - name: Install Unity
        if: ${{ steps.unity-cache.cache-hit }} == false
        run: |
          brew install --cask unity

      - uses: ./
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          ulf-file-base64: ${{ secrets.LICENSE_FILE_BASE64 }}
